### ISSUE TITLE
Table Column for Year and Type are too small

### ISSUE THREAD

**Issue by ingosiegert** [martinec/grav-plugin-bibtexify#10]
When generating the table for my publiations, year and type get so small, that the text get wrapped. How can this be fixed?

**Comment by martinec** [comment]
This depends of your css. For example, you can increase the cell font-size using:

```css
.bibtable td {
  font-size: 1.1em;
}
```

**Comment by ingosiegert** [comment]
I, sorry, my description was maybe unclear. Not the font gets to small, but the width of the year and table rows, see the attached scren-shot
![Screenshot_20210412_203526](https://user-images.githubusercontent.com/62608505/114443987-a6dcf980-9bce-11eb-9c25-688b8a44c91b.png)

**Comment by martinec** [comment]
What about using `min-width`, for example:

```css
.bibtable td:nth-child(1) {
  min-width: 4em;
}

.bibtable  td:nth-child(2) {
  min-width: 8em;
}
```

Anyway, keep in mind that the issue does not come directly from this plugin, but probably from your main stylesheet or other css stylesheet.
