### ISSUE TITLE
Not working on modular page or custom field

### ISSUE THREAD

**Issue by educedesign** [martinec/grav-plugin-bibtexify#8]
Hi,

I installed your plugin on my grav page and tried the following example code inside a modular page: 

```
[bibtexify hideMissing=true]
@InBook{Gross1994,
  pages     = {2195--2205},
  title     = {The Encyclopedia of Language and Linguistics},
  publisher = {Oxford/NewYork/Seoul/Tokyo: Pergamon},
  year      = {1994},
  author    = {Gross, Maurice},
  editor    = {Ashley, R.E.},
  url       = {http://kybele.psych.cornell.edu/~edelman/TAU-05/Gross-french-lexicon-94.pdf},
}

@Article{Gross1998,
  author  = {Gross, Maurice},
  title   = {La fonction sémantique des verbes supports},
  journal = {Travaux de linguistique},
  year    = {1998},
  volume  = {37},
  pages   = {25--46},
  url     = {http://cat.inist.fr/?aModele=afficheN&cpsidt=2019110},
}

@Article{Gross2001b,
  author    = {Gross, Maurice},
  title     = {Les ambiguïtés},
  journal   = {Lingvisticae Investigationes},
  year      = {2001},
  volume    = {24},
  number    = {1},
  pages     = {3--41},
  publisher = {Amsterdam/Philadelphia : Benjamins},
  url       = {http://cat.inist.fr/?aModele=afficheN&cpsidt=13543081},
}
[/bibtexify]

```
When doing so, I receive the following (scoping?) error:

```
(index):300 Uncaught ReferenceError: bibtexify is not defined
    at HTMLDocument.<anonymous> ((index):300)
    at i (jquery-2.x.min.js:2)
    at Object.add [as done] (jquery-2.x.min.js:2)
    at e.fn.init.n.fn.ready (jquery-2.x.min.js:2)
    at (index):299
    at (index):304
(anonymous)	@	(index):300
i	@	jquery-2.x.min.js:2
add	@	jquery-2.x.min.js:2
n.fn.ready	@	jquery-2.x.min.js:2
(anonymous)	@	(index):299
(anonymous)	@	(index):304
```

Using the same code on a non-modular page works perfectly fine. Is there a setting I am missing for modular pages?

Thanks!

**Comment by educedesign** [comment]
I did some digging around and it seems the bibtexify CSS and JS files are not loaded in the header when using the shortcode on a modular page. For now I included

`<link href="http://localhost/user/plugins/bibtexify/css/bibtexify.css" type="text/css" rel="stylesheet">`

and 

`<script src="http://localhost/user/plugins/bibtexify/js/bibtexify.js"></script>`

in my `base.html.twig` header and everything works fine.

**Comment by educedesign** [comment]
I also just ran into the issue that the shortcode is not working inside a custom field. Inside my site.yaml I have the following setup:

```
title: Use Cases #Create new tab blueprint called Use Cases
'@extends':
  type: default #it extends the default blueprint

form:
  fields:
    tabs:
      type: tabs #Type is a tab
      active: 1

      fields:
        gallery:
          type: tab
          title: Use Cases #Set the title of the tab to 'Use Cases'

          fields:
            header.usecases:
              type: list #Create a list
              label: Case Study #called 'Use Case'
              fields: #declare the fields for each list item
                .title: #name
                  type: text #is of the type text
                  label: Case Study Title #called 'Use Case Title'
                .intro: #description
                  type: editor #textarea is a text editor
                  label: Case Study Introduction (~65 words) #called 'Use Case Introduction'
                .desc:
                  type: editor #this is a text editor
                  label: Case Study Description #called 'Use Case Description'
                .featured: #images
                  type: filepicker #allows you to select a file
                  folder: 'self@'
                  label: Select a feature image
                  preview_images: true
                  accept:
                    - .png
                    - .jpg
                    - .jpeg
                .pub:
                  type: editor
                  label: publications (bibtexify)

```

And I am using `{{ usecase.pub }}` to pull the content from the custom field `usecase.pub`. However, I only see the the actual shortcode I put into my custom field.
Using `{{ usecase.pub|shortcodes }}` gives me the following JS prompt when loading the page:

> localhost says
> DataTables warning: Unable to re-initialise DataTable. Please use the API to make any configuration changes required.
